spring:
  application:
    name: git
  datasource:
    url: jdbc:mysql://localhost:3306/git
    name:
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      jdbc-url:  jdbc:mysql://localhost:3306/git
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
